apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mynginx
        tier: mynginx
    spec:
      containers:
      - image: kparashar/mynginx:latest
        name: mynginx
        ports:
        - containerPort: 80
          name: mynginx
---
apiVersion: v1
kind: Service
metadata:
  name:  mynginx-service
  labels:
    app: mynginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: mynginx
  type: NodePort

