apiVersion: extensions/v1beta1
kind: Pod
metadata:
   name: mynginx
spec:
  replicas: 1
  selector:
       app: mynginx
  template:
  metadata:
    labels:
      app: mynginx
spec:
    containers:
    - name: mynginx
      image: kparashar/mynginx
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
spec:
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
  selector:
     app: mynginx

